### ISSUE TITLE
I need requirement & readme 

### ISSUE THREAD

**Issue by Kotori373** [lhpt2/GenreGAN#1]
Could you please give me a "requirement.txt" and a "readme" on how to train it?

**Comment by lhpt2** [comment]
Sorry for the late answer.

I've updated the README.md to provide a rough overview. Some parts of the code in the root directory ``plotloss.py`` or ``convert_dataset.py`` have to be tweaked for custom use as there is some things commented out (showing the plot) or hardcoded paths to dataset locations that are not part of the repo.

I don't know if I can provide a proper requirements.txt right away, it's been some time since I used the code and I cannot easily test it. The most important deps are ``soundfile`` ``tensorflow`` and ``torch``. Tensorflow has to be installed apart from Python too I think (the C/C++ shared libraries) so I would advise to follow the instructions on their website.

**Comment by lhpt2** [comment]
Allright, I autogenerated a ``requirements.txt`` from the imports in the filetree. There could still be issues introduced by versioning as I'm not sure if the versions of the packages are compatible or if there are newer versions that introduce changes in their API, but this is the best I can offer. You should be able to get it to work with some investigation though, maybe it also works right away.
